version: '2'

services:
  setup:
    # just one command so the execution take place in the same context
    command: bash -c "virtualenv . && source ./bin/activate && pip install -r requirements.txt"
    image: data.python3:1
    build:
      dockerfile: docker/python/Dockerfile
      context: ./
    volumes:
      - ./:/opt/app

  cleaner:
    # activate the virtualenv before starting the cleaner
    command: bash -c "source ./bin/activate && python src/cleaner.py"
    image: data.python3:1
    environment:
      - CLEANED_FOLDER=cleaned
      - SOURCE_FOLDER=samples
    volumes:
      - ./:/opt/app

  collector:
    # activate the virtualenv before starting the cleaner
    command: bash -c "source ./bin/activate && python src/collector.py"
    image: data.python3:1
    environment:
      - CLEANED_FOLDER=cleaned
      - TAGS_FILE=config/sample-tags.json
      - EXPENSE_ACCOUNT=expenses
      - INCOME_ACCOUNT=income
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=collector
      - DB_COLLECTION_NAME=collected
    volumes:
      - ./:/opt/app
    depends_on:
      - mongodb

  goxfer:
    command: go run src/goxfer.go
    image: data.golang1.9:1
    build:
      dockerfile: docker/golang/Dockerfile
      context: ./
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=collector
      - DB_COLLECTION_NAME=collected
      - BUXFER_API_ENDPOINT="https://www.buxfer.com/api/"
      - BUXFER_USERNAME=your_buxfer_username
      - BUXFER_PASSWORD=your_buxfer_password
    volumes:
      - ./:/opt/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.4
    volumes:
     - db_mongo:/data/db

volumes:
  db_mongo: