version: '2'

services:
  collector:
    command: "python src/main.py"
    image: collector.python3:1
    build:
      dockerfile: docker/Dockerfile
      context: ./
    ports:
      - '8080:8080'
    environment:
      COLLECTOR_ENV: 'development'
    volumes:
      - ./src:/opt/app