version: '2'

services:
  cleaner:
    command: "python cleaner.py"
    image: data.python3:1
    build:
      dockerfile: docker/python/Dockerfile
      context: ./
    volumes:
      - ./src:/opt/app

  collector:
    command: "python collector.py"
    image: data.python3:1
    build:
      dockerfile: docker/python/Dockerfile
      context: ./
    volumes:
      - ./src:/opt/app